/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"
#include "rcc.h"
#include "gpio.h"

#define myLEDport	GPIO_PORT_C
#define myLEDpin	GPIO_PIN_13

int main(void)
{
    F1_System_Init(HSE_72MHZ, SYSTICK_1KHZ);
    F1_GPIO_Pin_Setup_OUT(GPIO_PORT_C, GPIO_PIN_13, GPIO_OUTPUT_10MHZ, GPIO_OUTPUT_PP);
    while(1)
    {
	F1_GPIO_Pin_Toggle(GPIO_PORT_C, GPIO_PIN_13);
	F1_delay_ms(1000);

    }
}




















